### ISSUE TITLE
Usage message

### ISSUE THREAD

**Issue by DanielHeath** [cjheath/activefacts-compositions#15]
Running `schema_compositor` does nothing (appears to be a synonym for `/bin/true`). 

A usage message / suggestion to try `--help` would probably be better.

Running `schema_compositor --help` tells me there are a variety of compositors and generators, but not how to invoke them.

It would aid usage if the help message started with something like:
```
Usage: schema_compositor --<compositor> --<generator> [cql file]
```

**Comment by cjheath** [comment]
Update to activefacts-compositions-1.9.21.
It now provides help text for every compositor and generator, and does that when no arguments are given.
It also enumerates the available input handlers.
