### ISSUE TITLE
Rails model generator doesn't play nice with automatic reloading

### ISSUE THREAD

**Issue by DanielHeath** [cjheath/activefacts-compositions#18]
It'd be good to generate all these things to separate files in a sensible directory, so the rails autoloader could find it.

**Comment by cjheath** [comment]
Use the options to the models generator. I use this:
--rails/models=concern=Relations,output=app/models/relations

**Comment by cjheath** [comment]
Also need to use surrogates option to the compositor:
--relational=surrogates

**Comment by cjheath** [comment]
Also, nearly all the compositors and generators provide help:
`schema_compositor --rails/models=help`

**Comment by DanielHeath** [comment]
Yep - that does help. I'll try & write some 'story' documentation (as distinct from specification documentation).

**Comment by cjheath** [comment]
Have a play with the new glossary generator also:
`schema_compositor --relational=surrogates --doc/glossary myfile.cql`
