### ISSUE TITLE
Include generator command in warning comments

### ISSUE THREAD

**Issue by DanielHeath** [cjheath/activefacts-compositions#19]
Currently files get `# Auto-generated from CQL, edits will be lost` prepended to them.

I propose starting them with:

`# Auto-generated from 'bundle exec schema_compositor --relational=surrogates --rails/models=concern=Relations,output=app/models/relations warehouse.cql', edits will be lost`.

**Comment by cjheath** [comment]
Well, we can't assume they're necessarily using bundler, of course.
Also, I actually check that the file contains the header line before over-writing it,
so unless you actually retain that line, your work is safe.
But I could put the command line on the second line I suppose. What do you think?

**Comment by DanielHeath** [comment]
I just think it's useful to know how something was generated; ideally in an automated way so that it can't be wrong.

**Comment by cjheath** [comment]
Done, also for --rails/schema
